### ISSUE TITLE
ERROR: string indices must be integers

### ISSUE THREAD

**Issue by tairosonloa** [benkehoe/aws-sso-util#73] opened 2022-09-09 22:36 UTC
Getting the following error when doing:

```sh
$> aws-sso-util login --profile myprofile # finishes ok
$> aws-sso-util  credential-process --profile myprofile --debug
ERROR: string indices must be integers
```

aws-sso-util: 4.28.0
python: 3.8.9
MacOs Monterey 12.5.1

**Comment by benkehoe** [comment] 2022-09-12 14:35
Closed as a duplicate of #70, fixing this soon.

**Closed by benkehoe** 2022-09-12 14:35 UTC
